# Generated by Django 2.2.28 on 2024-12-05 12:19

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0003_auto_20241126_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2024, 12, 5, 15, 19, 36, 13401), verbose_name='Дата комментария'),
        ),
        migrations.CreateModel(
            name='VideoGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название игры')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.FileField(default='temp.jpg', upload_to='', verbose_name='Путь к картинке')),
                ('genres', models.CharField(max_length=100, verbose_name='Жанры')),
                ('developer', models.CharField(max_length=100, verbose_name='Разработчик')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('posted', models.DateTimeField(db_index=True, default=datetime.datetime.now, verbose_name='Опубликована')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'видеоигра',
                'verbose_name_plural': 'видеоигры',
                'db_table': 'VideoGames',
                'ordering': ['-posted'],
            },
        ),
    ]
