# Generated by Django 2.2.28 on 2024-12-05 12:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20241205_1523'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videogame',
            options={'verbose_name': 'видеоигра', 'verbose_name_plural': 'видеоигры'},
        ),
        migrations.RemoveField(
            model_name='videogame',
            name='author',
        ),
        migrations.RemoveField(
            model_name='videogame',
            name='description',
        ),
        migrations.RemoveField(
            model_name='videogame',
            name='developer',
        ),
        migrations.RemoveField(
            model_name='videogame',
            name='posted',
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2024, 12, 5, 15, 57, 50, 870115), verbose_name='Дата комментария'),
        ),
    ]
