# Generated by Django 2.2.28 on 2024-12-05 13:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20241205_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='videogame',
            name='description',
            field=models.TextField(default='', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2024, 12, 5, 16, 29, 29, 24977), verbose_name='Дата комментария'),
        ),
    ]
