# Generated by Django 2.2.28 on 2024-12-10 08:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20241210_1143'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Экшн', 'Экшн'), ('Приключение', 'Приключение'), ('Стратегия', 'Стратегия'), ('Хорор', 'Хорор'), ('Песочница', 'Песочница'), ('Аркада', 'Аркада')], max_length=50, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2024, 12, 10, 11, 46, 40, 106614), verbose_name='Дата комментария'),
        ),
        migrations.RemoveField(
            model_name='videogame',
            name='genres',
        ),
        migrations.AddField(
            model_name='videogame',
            name='genres',
            field=models.ManyToManyField(to='app.Genre', verbose_name='Жанры'),
        ),
    ]
