# Generated by Django 2.2.28 on 2024-12-12 13:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20241212_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2024, 12, 12, 16, 9, 22, 323522), verbose_name='Дата комментария'),
        ),
    ]
