# Generated by Django 2.2.28 on 2024-12-15 11:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20241215_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2024, 12, 15, 14, 19, 6, 426460), verbose_name='Дата комментария'),
        ),
    ]
