# Generated by Django 2.2.28 on 2024-12-15 14:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_auto_20241215_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2024, 12, 15, 17, 35, 43, 516166), verbose_name='Дата комментария'),
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=100)),
                ('speed', models.IntegerField()),
                ('price', models.IntegerField()),
                ('service', models.IntegerField()),
                ('message', models.TextField()),
                ('average_rating', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.VideoGame')),
            ],
        ),
    ]
