# Generated by Django 2.2.28 on 2024-12-15 18:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_auto_20241215_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2024, 12, 15, 21, 32, 5, 447419), verbose_name='Дата комментария'),
        ),
    ]
